### ISSUE TITLE
Preemptive Authentication DavClient

### ISSUE THREAD

**Issue by ueler** [ical4j/ical4j-connector#28]
Hi,

we're using the ical4j-connector library in our project for accessing SabreDav (http://sabre.io/).
We would like to set preemptive authentication to true, since we then can avoid unnecessary 401 requests for every request we make. This results in a significant performance boost in our case. We have already tested if that would work by changing the `begin()` method in the class 
`net.fortuna.ical4j.connector.dav.DavClient`
Before our change:
```java
void begin() {
  httpClient = new HttpClient();
  httpClient.getParams().setAuthenticationPreemptive(false);
}
```

After our change:
```java
void begin() {
  httpClient = new HttpClient();
  httpClient.getParams().setAuthenticationPreemptive(true);
}
```

The change would work for us, but may of course not be desired by everyone who uses the library.

Would it be possible to make this boolean flag configurable?

Thanks!

**Comment by benfortuna** [comment]
sure no problem. i've created a PR #29 will probably merge shortly if it builds ok

**Comment by ueler** [comment]
That's cool! Thank you very much!

**Comment by stellingsimon** [comment]
@benfortuna: I love the way you're attending to this project. I'd like to make a small donation to show my appreciation, do you have a PayPal address?

Thanks for your work!

**Comment by benfortuna** [comment]
@stellingsimon thanks so much for the encouragement.

 I've added a qr code with a hyperlink on the ical4j website:

http://ical4j.github.io

If you click on the image it will go to PayPal donations to support the project. Many thanks for your support it is very much appreciated.

**Comment by benfortuna** [comment]
I've just released 1.0.0 which includes preemptive auth support. Let me know of any issues

**Comment by stellingsimon** [comment]
I just tested with 1.0.0 and it doesn't work. The reason is a bug on the following line:

https://github.com/ical4j/ical4j-connector/blob/8ef11f9f4839671817481410b0f3f38678599f8c/src/main/java/net/fortuna/ical4j/connector/dav/AbstractDavObjectStore.java#L78

```
"true".equals(Configurator.getProperty("ical4j.connector.dav.preemptiveauth"))
```
always evaluates to false, because `Configurator.getProperty("ical4j.connector.dav.preemptiveauth")` is of type `Optional`. The Java compiler doesn't catch the error because `equals(Object)` fits just fine.

This should work and keep `false` as default:

```
"true".equals(Configurator.getProperty("ical4j.connector.dav.preemptiveauth").orElse(false))
```

**Comment by benfortuna** [comment]
Yes, i forgot about the new Optional in latest ical4j lib.. I've applied the fix now hopefully won't be long before 1.0.1 is available. Thanks.

**Comment by stellingsimon** [comment]
@benfortuna I realize not much else has happened in this repo, but it's been a month since the second fix has been included, and we're eager to start using this optimization as it would heavily speed up some of our batch-insertion code. Would you consider releasing a 1.0.1 so that we can use this few feature? Thanks!

**Comment by benfortuna** [comment]
@stellingsimon 1.0.1 has already been released on March 24, you can find it in maven central.

 Apologies I didn't provide a notification. Let me know if it works for you or if further changes required.

**Comment by stellingsimon** [comment]
lol, how stupid of me. I must have missed it by just a few hours or so. Anyway, the fix is complete and all is well now, thanks!

**Comment by ASchmidt84** [comment]
Hi,
i am using version 1.0.4 and have the same error:
```
java.lang.NoSuchMethodError: 'net.fortuna.ical4j.util.Optional net.fortuna.ical4j.util.Configurator.getProperty(java.lang.String)'
```
I try this code
```
val cal = new CalDavCalendarStore("-//Ben Fortuna//iCal4j Connector 1.0//EN",new URL(url),PathResolver.ICAL_SERVER)
      cal.connect(userName,password.toCharArray)
      cal.getCollections.asScala.foreach(r => println(r.getDisplayName))
```
Do you have anywhere a tutorial for connecting?

Thank you.

**Comment by benfortuna** [comment]
@ASchmidt84 can you provide a full stack trace for the error? 

Note that I'm currently working on a version 2 of this library that will see a major refactor of the code. So I'm planning to provide better documentation/examples once that is complete. In the meantime you can try looking at the unit tests for examples.

**Comment by ASchmidt84** [comment]
Hi @benfortuna 
i enjoy your plan to write a new version.
This is the full stacktrace. I have nor more information. 😢 
Also instead of a scala util.Try I used a java try and catch and my only information is that. 
I follwed the implmentation and saw in constructor the method call super(...). Also followed this I can see the same call of
```
Configurator.getProperty("ical4j.connector.dav.preemptiveauth")
```
I am a little bit confused. Why are you using properties? Would it be better to use this as parameter, wouldnt it?
Hope it could help. André
